### ISSUE TITLE
false positive: subtest (t.Run) detected since v0.2.0

### ISSUE THREAD

**Issue by johejo** [kulti/thelper#15]
Hi.
Thanks for the wonderful linter.
I found something like false positive at v0.2.0.

main_test.go
```go
package main

import "testing"

func Test(t *testing.T) {
	t.Run("sub", func(t *testing.T) {})
}
```

```sh
$ go install github.com/kulti/thelper/cmd/thelper@v0.1.0
$ thelper ./...
```

```sh
$ go install github.com/kulti/thelper/cmd/thelper@v0.2.0
$ thelper ./...
/path/to/main_test.go:6:15: test helper function should start from t.Helper()
```

**Comment by kulti** [comment]
Hi,

thank you for your feedback!

I've added anonymous functions checking in v0.2.0. I've thought about smth like this:
```
func Test(t*testing.T) {
	check := func(t *testing.T) {
		// ...
	}

	// do smth
	check(t)

	// do smth more
	check(t)
}
```

And haven't thought about sub-test case. Aftre your suggestion, I think that the following is false-positive too:
```
func Test(t *testing.T) {
	t.Run("sub", check)
}

func check(t *testing.T) {
	// ...
}
```

Looks like any function used as a sub-test should be skipped.

What do you think?

**Comment by johejo** [comment]
>Looks like any function used as a sub-test should be skipped.

Agree.
