### ISSUE TITLE
add --fix support

### ISSUE THREAD

**Issue by kulti** [kulti/thelper#3]
It's possible to auto fix thelper issues.

**Comment by shehrozkhan88** [comment]
#4

**Comment by kulti** [comment]
It will not fix.

Automatic fixes are hard to implement.
1. go AST cannot format source good enough after some fixes inside the tree. I've found the [issue](https://github.com/golang/go/issues/20744) and the [solution with DST](https://github.com/dave/dst).
2. DST is hard to use with Inspector. Sometimes it looks impossible.
3. Inspector saves a lot of time to parse AST because the results can be reused. And it's the preferred way to write a linter.

So I decide, that fix linter's warning is not hard enough to automize it. In the future, if AST will be improved I can reopen this issue.
