### ISSUE TITLE
False positive: fuzz tests

### ISSUE THREAD

**Issue by peterebden** [kulti/thelper#34]
I've run across a couple of false positives relating to fuzz tests:
```
package test

import (
	"testing"
)

func FuzzTest(f *testing.F) {
	f.Add("something")
	f.Fuzz(func(t *testing.T, in string) {   // lint warning is here
	})
}
```
This emits `test helper function should start from t.Helper()` for the internal function; presumably since fuzz tests are relatively new, thelper doesn't understand them like it does for normal subtests?

Thanks for the tool - has found a few cases where I can improve my test's output!

**Comment by kulti** [comment]
Thank you for the report. Nice to hear that tool is useful for you!

I've merge a fix to master. It needs a little more time to bump version and support it in golangci-lint. If you can test master version of thelper on your cases it will be really helpful.

**Comment by peterebden** [comment]
Thanks for the quick fix!

I've tried running from latest master but am getting errors about `internal error: package "testing" without types was imported`. I'll keep trying for a bit though :)

**Comment by kulti** [comment]
Thank you for testing! I should find this by myself before merging fix 🙃

At now it should work fine.

**Comment by peterebden** [comment]
Ah great - yes can confirm it works fine now. Thanks again!
