### ISSUE TITLE
linter setting to configure exceptions

### ISSUE THREAD

**Issue by hedhyw** [kulti/thelper#41]
## Why?
Testing frameworks can provide special syntax that can generate false linter warnings.

## How?
So there are several ways to solve it:
- Add `// nolint: thelper // Not a helper.` to any exception, but it is not the best idea if there are many tests...
  Naive disabling of linter for the entire file, also so-so, because it may still have helpers.
- Once configure common pattern exceptions in linter-settings of golangci-lint config. It is my suggestion.
- Hard-code exceptions in `thelper`. Too many cases to handle, so not really an option.

Relates to https://github.com/hedhyw/gherkingen/issues/51

**Thank you for the linter!**

**Comment by kulti** [comment]
Thank you for your suggestion.

If you are using golangci-lint you already have configuration file and can configure common pattern exceptions. You can find some examples [here](https://gist.github.com/kulti/25f9243939e699428f7e14c5a3c8c32c#file-golangci-yml-L151) and [here](https://golangci-lint.run/usage/configuration/#issues-configuration).

I'm not sure that this functionality should be implemented twice in the linter and the meta-linter. In most cases projects use golangci-lint.
