### ISSUE TITLE
t.Helper() should not be mandatory when already called from an helper.

### ISSUE THREAD

**Issue by didrocks** [kulti/thelper#42]
In this following situation:

```
func TestSmth(t *testing.T) {
	checkSmth(t)
}


func checkSmth(t *testing.T) {
	t.Helper()
        checkSmthElse(t)
}

func checkSmthElse(t *testing.T) {
}
```

`checkSmthElse`, as only be called by another function being marked with t.Helper() and not directly by any tests does not need t.Helper(), as the test will always fail (in that case), on the `checkSmth(t)` call.

Right now, the helper requires `checkSmthElse` to be annoted too.

**Comment by kulti** [comment]
Sorry for delayed reply.

The idea of `t.Helper()` is to mark all helper functions to show fail-point inside test function. So, all non-test function should be marked as `t.Helper()`.

Imagine in your example `checkSmthElse` has the following implementation:
```
func checkSmthElse(t *testing.T) {
	t.Helper()
	t.Fatalf("tuc")
}
```
In that case failed test show that if failed inside `TestSmth` on the line with call `checkSmth`. Without `t.Helper()` it shows that test was failed inside `checkSmthElse` on `t.Fatalf` row.

**Comment by didrocks** [comment]
No worry on the delay and thanks for the answer! Actually, you are right, I thought the failure would bubble up to first `t.Helper` that is encouters, shielding the children functions called from this helper, but it seems it doesn't (I’m surprised because I’m sure it did with an older version of Go).

Closing thus. Sorry for the annoyance!
