### ISSUE TITLE
Allow context.Context as first argument

### ISSUE THREAD

**Issue by zikaeroh** [kulti/thelper#9]
I have test helpers that use both contexts and `testing.T`. There's a bit of style ambiguity regarding which one comes first. I always put the context first, and then the `testing.T` second, but I see messages like:

```
internal/birc/fakeirc/helper.go:43:1: parameter *testing.T should be the first (thelper)
func NewHelper(ctx context.Context, t *testing.T, opts ...Option) *Helper {
^
internal/pkg/apiclient/twitch/channel_test.go:442:1: parameter *testing.T should be the first (thelper)
func tokFor(ctx context.Context, t *testing.T, tw *twitch.Twitch, ft *fakeTwitch, id int64) *oauth2.Token {
^
internal/pkg/apiclient/twitch/dead_token_test.go:59:1: parameter *testing.T should be the first (thelper)
func invalidRefreshTokFor(ctx context.Context, t *testing.T, tw *twitch.Twitch, ft *fakeTwitch, id int64, refresh string) *oauth2.Token {
```

If I swap them, then golint itself complains:

```
internal/birc/fakeirc/helper.go:43:1: context.Context should be the first parameter of a function (golint)
func NewHelper(t *testing.T, ctx context.Context, opts ...Option) *Helper {
```

It'd be nice if for purposes of this analyzer that the context is ignored; I don't exactly want to fight golint.

**Comment by kulti** [comment]
Thank you for testing thelper linter!

I've thought about that compatibility with context linter and not found any appropriate solution. After your suggestion I think "ctx the first" is more common, so "t the second if ctx the first" is a good exception for thelper linter.

It will be done in next release. At now you can use nolint for that specific helpers or configure thelper to stay only with t_begin and t_name checks.

**Comment by zikaeroh** [comment]
Yup, I've done so already. Thanks!
